name: porto_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

command:
   bootstrap:
      usePubspecOverrides: true
   flutterSdkVersion: ^3.6.2

scripts:
  build:
    run: |
      dart pub run build_runner build --delete-conflicting-outputs
