name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^9.3.0+1
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  data_channel: ^2.0.0+1
  dartz: ^0.10.1
  kt_dart: ^1.1.0
  flutter_gen_runner: ^5.4.0
  shared_preferences: ^2.2.2
  connectivity: ^3.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.3.3
  string_validator: ^1.0.2
  intl: ^0.20.2
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_analytics: ^11.4.2
  firebase_crashlytics: ^4.3.2
  firebase_remote_config: ^5.4.0
  firebase_performance: ^0.10.1+2

  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.3.0
  package_info_plus: ^8.2.1
  awesome_dio_interceptor: ^1.1.0
  colorize: ^3.0.0
  image_picker: ^1.0.8
  url_launcher: ^6.2.5
  webview_flutter: ^4.8.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.1
  flutter_image_compress: ^2.3.0

  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  encrypt: ^5.0.3
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  android_intent_plus: ^5.3.0
  path_provider: ^2.1.5
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_dynamic_links: ^6.1.2
  firebase_app_check: ^0.3.2+2
  google_sign_in: ^6.2.2
  flutter_gen: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.14
  injectable_generator: ^2.7.0
  auto_route_generator: ^9.3.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/csv/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100



  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
flutter_gen:
  output: lib/widget/utils
  line_length: 8000